apiVersion: v1 
kind: Service
metadata: 
   name: result-service
   labels: result-service
   app: demo-voting-app
spec:
  ports:
    - port: 80
      targetport: 80
  selector:
    name: result-app-pod
    app: demo-voting-app