apiVersion: v1 
kind: Service
metadata: 
   name: redis
   labels: redis-service
   app: demo-voting-app
spec:
  type: Nodeport
  ports:
    - port: 80
      targetport: 80
      nodeport: 30004
  selector:
    name: voting-app-pod
    app: demo-voting-app